### ISSUE TITLE
Add AuthorisationURL-Generation and Analysis

### ISSUE THREAD

**Issue by Frank-Wiebeler** [DKE-Data/agrirouter-api-java#10]
FMIS and Telemetry platforms need to perform the authorisation process. Would be good to have a class  to analyse the result delivered through the Redirect GET-Call.

Please add this

**Comment by saschadoemer** [comment]
@Frank-Wiebeler Still necessary?

**Comment by Frank-Wiebeler** [comment]
Implemented with #51 , wording adjusted with  #61
