### ISSUE TITLE
Add Technical Message Types for Telemetry System Calls

### ISSUE THREAD

**Issue by Frank-Wiebeler** [DKE-Data/agrirouter-api-java#13]
The file  agrirouter-api-java/agrirouter-api-java-api/src/main/kotlin/com/dke/data/agrirouter/api/enums/TechnicalMessageType.kt includes an enum of all technical message types.

Please add the TMT for onboarding and offboarding of virtual CUs

**Comment by saschadoemer** [comment]
Part of #29 - therefore closed.
