### ISSUE TITLE
OnboardingException message field is null.

### ISSUE THREAD

**Issue by istvangal-agco** [DKE-Data/agrirouter-api-java#130]
**Describe the bug**
The OnboardingException class does not contain message (the value is null in the parent), only a lastError field which has not getter. 

**To Reproduce**
https://github.com/DKE-Data/agrirouter-api-java/blob/develop/agrirouter-api-java-api/src/main/java/com/dke/data/agrirouter/api/exception/OnboardingException.java

**Expected behavior**
I would like to have the message field filled, e.g. pass the message to the parent constructor.

**Comment by saschadoemer** [comment]
Dear @istvangal-agco,

please check the solution the following PR #131 - if that one suits you, please let me know.

Regards

Sascha

**Comment by saschadoemer** [comment]
Closed with PR #131.
