### ISSUE TITLE
Routerdevice went offline after a month

### ISSUE THREAD

**Issue by istvangal-agco** [DKE-Data/agrirouter-api-java#132]
**Routerdevice went offline after a month**
I set up a connection via MQTT to a RouterDevice. This worked fine, but after a month it went offline.

These Routerdevices are under Lukas account.
Account ID: 706825a0-f769-4f17-bf2e-bbec80bbb93a

**To Reproduce**
1. Go to ' https://agrirouter-qa.cfapps.eu10.hana.ondemand.com/app#RouterDevice-Display '
2. Click on ' a routerdevice which has offline state, download the certficiate '
3. Try to connect via MQTT Routerdevice

**Expected behavior**
As I see, the routerdevice should not go offline.
If it goes offline, I don't see the opportunity to bring it back online

**Screenshots**
![image](https://user-images.githubusercontent.com/65231197/93778405-29e43580-fc26-11ea-8a14-2546b22d7bad.png)

**Comment by istvangal-agco** [comment]
@saschadoemer mentioned you, as you requested.

**Comment by saschadoemer** [comment]
@istvangal-agco This behavior is not part of the SDK right here, therefore I will close the issue. Anyway there is an open issue left for the AR team.
