### ISSUE TITLE
Allow access to RevokingException lastError

### ISSUE THREAD

**Issue by agrancaric-agco** [DKE-Data/agrirouter-api-java#136]
**Describe the bug**
RevokingException doesn't have a getter for lastError and message is null so it is not possible to access error details without using reflection. 

**To Reproduce**
https://github.com/DKE-Data/agrirouter-api-java/blob/master/agrirouter-api-java-api/src/main/java/com/dke/data/agrirouter/api/exception/RevokingException.java

**Expected behavior**
Ideally it would provide a method that would return RevokingError directly without need to parse it using RevokingService similarly to OnboardingException and OnboardingError behaviour, but if not just a getter would be enough.

**Comment by saschadoemer** [comment]
@agrancaric-agco Since the API module has no access to the service layer, parsing the error code directly would not be the best idea. I added some getters for both of the exceptions.

**Comment by saschadoemer** [comment]
Please see https://github.com/DKE-Data/agrirouter-api-java/pull/137 for more details and leave your review.

**Comment by agrancaric-agco** [comment]
> @agrancaric-agco Since the API module has no access to the service layer, parsing the error code directly would not be the best idea. I added some getters for both of the exceptions.

Hi, thanks for the fix, just wanted to check since maybe we didn't understand each other? I was thinking that a property RevokingError is added to the exception and then the service layer fills the RevokingError directly in RevokingException instead of putting the JSON there. This is the behaviour in https://github.com/DKE-Data/agrirouter-api-java/blob/master/agrirouter-api-java-api/src/main/java/com/dke/data/agrirouter/api/exception/OnboardingException.java. Am I missing something?

**Comment by saschadoemer** [comment]
@agrancaric-agco Please check the latest PR (#137) this should meet your needs, I would say.

**Comment by agrancaric-agco** [comment]
> @agrancaric-agco Please check the latest PR (#137) this should meet your needs, I would say.

Yes, thats it, thanks.
