### ISSUE TITLE
Remove or generalize assertResponseStatusIsValid from Services like SetCapabilitiesServiceImpl

### ISSUE THREAD

**Issue by Frank-Wiebeler** [DKE-Data/agrirouter-api-java#14]
assertResponseStatusIsValid checks for one specific Response code. This is good for testing the agrirouter, for the api however, it should be more generalized, as not only HTTP200 but every HTTP2xx response indicates, that the request succeeded. Throwing an Error here is not correct. 

Either check a range from 200 to 299 or remove the assert at all. Services to handle the Request-Result (not the response from the outbox) could be an additional step

**Comment by saschadoemer** [comment]
Should be resolved with #50.

**Comment by saschadoemer** [comment]
Please re-open if there are any other places to correct.
