### ISSUE TITLE
Remove duplicated MessageID generation, return applicationMessageID "somehow"

### ISSUE THREAD

**Issue by Frank-Wiebeler** [DKE-Data/agrirouter-api-java#16]
This requirement meets all ServiceImplementations sending requests to the agrirouter.
In most of the implementation, there is a messageID generated in the send-message, which is not really required. Additionally, the applicationMessageId, which is returned from agrirouter with the Response to the request is generated inside encodemessage but never returned to the application implementing this. Therefore, it is currently not possible, to trace responses to a request as the applicationMessageID is not reachable for an implementation.

Please optimize that.

**Comment by matjansen** [comment]
Wasn't the first part (unnecessary generation of a `messageID`) resolved with https://github.com/DKE-Data/agrirouter-api-java/commit/49bbf9ee0b9927db0cc8a336451c9a431045acba?

**Comment by Frank-Wiebeler** [comment]
Done with PullRequest #42 and #43
