### ISSUE TITLE
Release Version 

### ISSUE THREAD

**Issue by manedev79** [DKE-Data/agrirouter-api-java#78]
Hi guys,
from the docs I saw that you provide a snapshot Version of the library in the sonatype repo. Are there plans to provide a release version and in so when would that be?

**Comment by saschadoemer** [comment]
Hey,

we could provice a release version after the MQTT implementation is integrated - probably next wwek.

Regards!

Sascha

**Comment by manedev79** [comment]
Hi Sascha,
Thanks for the quick reply. I'll check back next week then.

Sascha Doemer <notifications@github.com> schrieb am Mo., 10. Juni 2019,
12:23:

**Comment by saschadoemer** [comment]
Sorry for the long response time...

This night I was able to finish the release prep and pushed the artifacts to the maven central.

![image](https://user-images.githubusercontent.com/1309344/66999671-bf9e4900-f0d6-11e9-9d7c-88ac93b207a3.png)

These are just the release candidates, but they work already.

**Comment by manedev79** [comment]
Thanks Sascha,
I'll check it out.
