### ISSUE TITLE
Agrirouter dependencies not available on Gradle Build

### ISSUE THREAD

**Issue by akurte** [DKE-Data/agrirouter-api-java#91]
**Describe the bug**
While integrating Agrirouter in our project we added the dependencies (api,impl,convenience) as stated in the readme.
On "gradle build" the dependencies (.jar files) are not available from the sonatype repo.

**To Reproduce**
Use a gradle project, add the following repo definition and dependencies and build it.

Repo definition:
`maven { 
    	url "https://oss.sonatype.org/content/repositories/snapshots"
    	mavenContent {
            snapshotsOnly()
        }
    }`

Dependendencies:
`compile group: "com.agrirouter.api.lmis", name: "agrirouter-api-java-api", version: "0.0.1-SNAPSHOT", classifier: "jdk8", changing: true`
	`compile group: "com.agrirouter.api.lmis", name: "agrirouter-api-java-impl", version: "0.0.1-SNAPSHOT", classifier: "jdk8", changing: true`
	`compile group: "com.agrirouter.api.lmis", name: "agrirouter-api-java-convenience", version: "0.0.1-SNAPSHOT", classifier: "jdk8", changing: true`

**Expected behavior**
Clean build without missing dependencies

**Desktop (please complete the following information):**
Building environment is Gradle 5.5.1 on Windows 10

**Additional context**
It seems that the underlying repo link to the JDK8 dependencies is mixed with the version of the JKD10 or JDK11 dependencies. Gradle tries to download from a link that matches the most recent updated resource in the given repo (in this case the JDK11 version) and just replaces the classifier with JDK8.
-> resource not found

**Comment by saschadoemer** [comment]
@akurte Could you attach a simple example as project? I"ll check on it.

**Comment by akurte** [comment]
@saschadoemer The requested project is attached. It was created with Eclipse and Buildship. Neither a build in Eclipse itself or via PowerShell does work.

![buildfail_console](https://user-images.githubusercontent.com/54102562/63014670-55c3b200-be8f-11e9-8f0c-fe5dbf6daddc.png)
![buildfail_eclipse](https://user-images.githubusercontent.com/54102562/63014688-5e1bed00-be8f-11e9-8b64-7c6fe275cdeb.png)

[AgrirouterDependencyDemo.zip](https://github.com/DKE-Data/agrirouter-api-java/files/3500944/AgrirouterDependencyDemo.zip)

**Comment by saschadoemer** [comment]
@akurte As far as I could see the dependencies are not pushed to the directory correctly. There"s only one version which can be found. I"ll have a look at that and keep you up to date. This behaviour did change with the last build.

**Comment by saschadoemer** [comment]
@akurte The deployment skripts for the last snapshot did fail - therefore the dependencies are currently missing. I will restart the logs and check on the outcome again - last error was a problem with the sonatype repos and access during the build.

**Comment by saschadoemer** [comment]
@akurte Seems to be a short outage of the sonatype repo during the last deployment into the snapshot repo. With the lastest build the dependencies should be resolved correctly - but I currently not a different problem with the SNAPSHOT resolving. The parent POM is deployed multiple times, therefore I could be the case, that you retrieve the wrong version during dependency resolution. This would be fixed by using a release version - which does not exist or changing the deployment mechnism. I"ll check on that as well.

**Comment by saschadoemer** [comment]
@akurte Nothing I can resolve today - current solution would be building the jars locally and install them to the local repo. I need to check multi release configurations for the maven release process to be sure about the deployment to sonatype.

**Comment by akurte** [comment]
@saschadoemer ok..we will download the latest jars from the sonatype repo and use them locally for now.
I hope this will be fixed soon ;)

**Comment by saschadoemer** [comment]
@akurte Soon...

This night I was able to finish the release prep and pushed the artifacts to the maven central.

![image](https://user-images.githubusercontent.com/1309344/66999671-bf9e4900-f0d6-11e9-9d7c-88ac93b207a3.png)

These are just the release candidates, but the shoul fix the error.

**Comment by akurte** [comment]
@saschadoemer works great..thanks
now the build is a lot easier ;)
