### ISSUE TITLE
Onboarding vCU after Offboarding the same vCU does not work

### ISSUE THREAD

**Issue by akurte** [DKE-Data/agrirouter-api-java#93]
**Describe the bug**
After offboarding a given vCU it is not possible to onboard it again later on.
The onboarding response is just empty but console output states that everything worked.

**To Reproduce**
1. onboard any vCU
2. offboard the same vCU
3. onboard the same vCU again

**Expected behavior**
Expected result is an OnboardingResponse or Exception instead of nothing.

**Desktop:**
 - OS: Windows 10
 - Browser: chrome

**Backend server:**
 - OS: Ubuntu 16.04.6 LTS

**Additional context**
It seems that the vCU does not really get deleted on the Agrirouter side.
The console output shows some repsonse from AR after onboarding the offboarded vCU, but no OnboardingResponse object is delivered in Java. The returned list is empty.

**Comment by Frank-Wiebeler** [comment]
Do you have an example implementation or could you post the response you get from agrirouter?

**Comment by akurte** [comment]
Steps which where executed before the screenshot was taken:
1) Onboarding account -> works fine (appears in Agrirouter "Kontrollzentrum")
2) Onboarding vCU (ExternalId e.g. urn:exatrek:adapter:12) -> works fine (vCU appears in Agrirouter "Kontrollzentrum")
3) Offboarding vCU -> works fine (vCU disappears in Agrirouter "Kontrollzentrum")
4) Onboarding vCU (with same ExternalId: urn:exatrek:adapter:12) -> can be seen on screenshot

![onboarding_after_offboarding](https://user-images.githubusercontent.com/54102562/63500310-f4709400-c4c9-11e9-9d48-146e8cf93e6d.png)

The result is an empy list of OnboardingRespons items and no Exception.

**Comment by Frank-Wiebeler** [comment]
Could you please post the output as text, so that I can base64-Decode it?

**Comment by akurte** [comment]
Here you go ;)

2019-08-22 10:31:35.106  INFO 30817 --- [nio-9090-exec-2] de.exatrek.portal.rest.AgrirouterRest    : Onboarding vCU...
2019-08-22 10:31:35.810  INFO 30817 --- [nio-9090-exec-2] o.g.jersey.logging.LoggingFeature        : 1 * Sending client request on thread ajp-nio-9090-exec-2
1 > POST https://dke-qa.eu10.cp.iot.sap/iot/gateway/rest/measures/28b9a81d-2ece-4c9f-b647-c97c63b9c921
1 > Accept: application/json,application/json
1 > Content-Type: application/json
{"sensorAlternateId":"bbd59e06-a5b1-4d41-83c0-5d30a0adfd91","capabilityAlternateId":"3701784d-58b8-4415-87a7-fb36badd41c6","measures":[{"message":"UQokNzNjMjY2MDUtYjg4YS00ZTAzLTk0OWItN2VkYTU0NjE0ZGY1EAEaG2RrZTpjbG91ZF9vbmJvYXJkX2VuZHBvaW50c0IKCIfe+eoFEMCEPV4KXAovYWdyaXJvdXRlci5jbG91ZC5yZWdpc3RyYXRpb24uT25ib2FyZGluZ1JlcXVlc3QSKQonChZ1cm46ZXhhdHJlazphZGFwdGVyOjUxEg1FWEEtVDJfMDAwMDAy","timestamp":"1566469895"}]}

2019-08-22 10:31:35.813  INFO 30817 --- [nio-9090-exec-2] o.g.jersey.logging.LoggingFeature        : 1 * Client response received on thread ajp-nio-9090-exec-2
1 < 200
1 < Content-Length: 0
1 < Date: Thu, 22 Aug 2019 10:31:35 GMT
1 < Server: Jetty(8.1.15.v20140411)
1 < Strict-Transport-Security: max-age=16000000; includeSubDomains; preload;

2019-08-22 10:31:36.008  INFO 30817 --- [nio-9090-exec-2] o.g.jersey.logging.LoggingFeature        : 1 * Sending client request on thread ajp-nio-9090-exec-2
1 > GET https://dke-qa.eu10.cp.iot.sap/iot/gateway/rest/commands/28b9a81d-2ece-4c9f-b647-c97c63b9c921
1 > Accept: application/json,application/json

2019-08-22 10:31:36.039  INFO 30817 --- [nio-9090-exec-2] o.g.jersey.logging.LoggingFeature        : 1 * Client response received on thread ajp-nio-9090-exec-2
1 < 200
1 < Connection: close
1 < Content-Type: application/json;charset=utf-8
1 < Date: Thu, 22 Aug 2019 10:31:36 GMT
1 < Server: Jetty(8.1.15.v20140411)
1 < Strict-Transport-Security: max-age=16000000; includeSubDomains; preload;
[]

2019-08-22 10:31:36.696  INFO 30817 --- [nio-9090-exec-2] o.g.jersey.logging.LoggingFeature        : 1 * Sending client request on thread ajp-nio-9090-exec-2
1 > GET https://dke-qa.eu10.cp.iot.sap/iot/gateway/rest/commands/28b9a81d-2ece-4c9f-b647-c97c63b9c921
1 > Accept: application/json,application/json

2019-08-22 10:31:36.734  INFO 30817 --- [nio-9090-exec-2] o.g.jersey.logging.LoggingFeature        : 1 * Client response received on thread ajp-nio-9090-exec-2
1 < 200
1 < Connection: close
1 < Content-Type: application/json;charset=utf-8
1 < Date: Thu, 22 Aug 2019 10:31:36 GMT
1 < Server: Jetty(8.1.15.v20140411)
1 < Strict-Transport-Security: max-age=16000000; includeSubDomains; preload;
[]

2019-08-22 10:31:37.380  INFO 30817 --- [nio-9090-exec-2] o.g.jersey.logging.LoggingFeature        : 1 * Sending client request on thread ajp-nio-9090-exec-2
1 > GET https://dke-qa.eu10.cp.iot.sap/iot/gateway/rest/commands/28b9a81d-2ece-4c9f-b647-c97c63b9c921
1 > Accept: application/json,application/json

2019-08-22 10:31:37.406  INFO 30817 --- [nio-9090-exec-2] o.g.jersey.logging.LoggingFeature        : 1 * Client response received on thread ajp-nio-9090-exec-2
1 < 200
1 < Connection: close
1 < Content-Type: application/json;charset=utf-8
1 < Date: Thu, 22 Aug 2019 10:31:37 GMT
1 < Server: Jetty(8.1.15.v20140411)
1 < Strict-Transport-Security: max-age=16000000; includeSubDomains; preload;
[{"sensorAlternateId":"bbd59e06-a5b1-4d41-83c0-5d30a0adfd91","capabilityAlternateId":"65963008-5919-45da-8557-4298e6a41152","command":{"message":"XgjJARALGiQ3M2MyNjYwNS1iODhhLTRlMDMtOTQ5Yi03ZWRhNTQ2MTRkZjUiJGVjMjkzNDBhLTZlOGMtNDUzNy05YTk5LThmYmMzNzAzNGE0NioLCIne+eoFEIDXzFqvAQqsAQpFdHlwZXMuYWdyaXJvdXRlci5jb20vYWdyaXJvdXRlci5jbG91ZC5yZWdpc3RyYXRpb24uT25ib2FyZGluZ1Jlc3BvbnNlEmMSYQoWdXJuOmV4YXRyZWs6YWRhcHRlcjo1MRJHCjlUaGVyZSBpcyBhbHJlYWR5IGFuIGV4aXN0aW5nIHZpcnR1YWwgQ1Ugd2l0aCBwcm92aWRlZCBpZC4SClZBTF8wMDAzMDY="}}]

**Comment by akurte** [comment]
The last message decoded says that the vCU already exists (was also my assumption) and it does not deleted properly in Agrirouter.
A workaround would be to use a different external id everytime this happens, but this will not solve the problem. It may also lead to multiple "zombie" vCUs in Agrirouter which are not connected (and somehow can not be reconnected) to an account.

**Comment by Frank-Wiebeler** [comment]
I think I understand the problem; we only fetch the first message that is returned and that's an ACK_WITH_MESSAGES in this case.

I'll check how to fix that (maybe not backwards-compatible), in the meanwhile you can just add some additional fetchMessageService.fetch to your code in case, the onboard-Command returns an empty list.

Could you confirm, that this workaround helps and that you receive additional messages?

**Comment by Frank-Wiebeler** [comment]
In that case I'ld say that our Java API is just the second level error and we would have to check agrirouter behavior about that. Could you please send a mail to the support@my-agrirouter.com with a bug report?
Please include the OnboardingRequest, the Onboarding Result, The offboarding request and result and the second onboarding Request including Result. Also add the applicationId, certificationVersionId and the endpoint of the telemetry platform, from which you are trying to onboard the VCUs. Also describe the behavior of the UI (is the VCU removed from the UI after you sent the offboarding request?)

Thank you.

**Comment by akurte** [comment]
I contacted the agrirouter support. They said that offboarding does not delete the vCU directly (just deactivates it). There is a internal Job which deletes this deactivated vCUs after some time.
So just taking a new UUID would fix the onboarding problem after offboarding.

But it would be better to just get some sort of notification instead of just no OnboardingResponse when onboarding ;)
Instead auf a returned list auf OnboardingResponses it woudl be nice to have a list of results (OnboardingResponse or Error or similar) matching the list of given endpointIds to onboard.

**Comment by agrirouter** [comment]
Thanks for the feedback. We will check it and optimize it as soon as possible.
